---
- name: Setting up NAS server
  become: yes
  hosts: omv
  roles:
    - roles/base
    - roles/open_media_vault
    - roles/lockdown
  vars_files:
    - ../vars/useraccounts.yml
    - ../vars/nas-settings.yml
