servername: my-nas
OMV_packages:
- openmediavault-keyring
- postfix
- openmediavault
OMV_repos:
- enable
- testing
- vbox
- plex
- greyhole
- vdr
- miller
- millertesting
- btsync
- vpn
- zfs
- gluster
- mono
- monotesting
- docker
- dockertesting
- hwraid
- beta
plugins_packages:
- openmediavault-fail2ban
- openmediavault-route
- openmediavault-lvm2
- openmediavault-minidlna
- openmediavault-clamav
- openmediavault-downloader
- openmediavault-couchpotato
- openmediavault-sickbeard
repo:
- 'deb http://packages.openmediavault.org/public stoneburner main'
NTPSERVER1: 0.ubuntu.pool.ntp.org
NTPSERVER2: 
NTPSERVER3: 
NTPSERVER4: 
NTPSERVER5:
########module vales########
clamav_settings:
  enable: "1"
  logclean: "1" 
  scanpe: "1"
  scanole2: "1"
  scanhtml: "1"
  scanpdf: "1"
  scanelf: "1"
  scanarchive: "1"
  detectbrokenexecutables: "1"
  algorithmicdetection: "1"
  ollowdirectorysymlinks: "1"
  followfilesymlinks: "1"
  followdirectorysymlinks: "1"
  detectpua: "1"
  extraoptions: ""
  freshclam:
    enable: "1"
    checks: "24"
time:
  enable: "1"
  timezone: 'Europe\/London'
minidlna:
  enable: "0"
  name: "Media Player on {{ servername }}"
  port: "8200"
  strict: "1"
  tivo: "1"
  shares: ""
  loglevel: "error"
  rootcontainer: "."
couchpotato:
  enable: "0"
  showtab: "0"
  branch: 'master'
  repo: 'https:\/\/github.com\/RuudBurger\/CouchPotatoServer.git'
  port: "5050"
sickbeard:
  enable: "0"
  ssl: "0"
  ppass: "0"
  repo: 'https:\/\/github.com\/midgetspy\/Sick-Beard.git'
  branch: "master"
  repo2: "Please choose a repository"
  branch2: "Please choose a branch"
  port: "8081"
  forks: ""
  newinstance: "0"
  newinstenable: "0"
  show_tab: "0"