---
- name: Generate firewall template
  template: src={{role_path}}/templates/firewall.Jinja2 dest=/tmp/firewall.Jinja2
  tags:
    - firewall
    - create_firewall_template


- name: add firewall to OMV
  shell: omv-config -m /config/system/network/iptables "`cat /tmp/firewall.Jinja2`"
  tags:
    - firewall
    - set_firewall_template


- name: Rebuild iptables config 
  shell: "omv-mkconf iptables"
  tags: 
   - firewall
   - update_firewall_config
