---
- name: Firewall setup
  fail:
    msg: "Installation works only on Debian 7 wheezy"
  when:
     ansible_distribution != "Debian" or
     ansible_distribution_major_version != "7" or
     ansible_distribution_release != "wheezy"
  tags: check