---
#- name: Set network (hostname)
#  shell: omv-config --modify /config/system/network '{"hostname": "{{ servername }}","domainname": "","interfaces": "","iptables": ""}'
#  tags: Setup network

- name: Set network (enable hostname)
  shell: "omv-config --modify /config/system/omvextrasorg/modules/hostname 1"
  tags: Setup network

#- name: Seting timezone to UTC
#  shell: omv-config --modify /config/system/time/timezone "UTC"
#  tags: Setup timezone

#- name: Set Time zone server
#  shell: omv-config --modify /config/system/time/timeservers "{{ NTPSERVER1 }}"
#  tags: Setup timezone

#- name: Enable NTP
#  shell: "omv-config --modify /config/system/time/enable 1"
#  tags: Setup timezone

- name: Config Clamav (detectbrokenexecutables)
  shell: "omv-config --modify /config/services/clamav/clamd/detectbrokenexecutables 1"
  tags: Setup clamav

- name: Config Clamav (followdirectorysymlinks)
  shell: "omv-config --modify /config/services/clamav/clamd/followdirectorysymlinks 1"
  tags: Setup clamav

- name: Config Clamav (followfilesymlinks)
  shell: "omv-config --modify /config/services/clamav/clamd/followfilesymlinks 1"
  tags: Setup clamav

- name: Enable Clamav
  shell: "omv-config --modify /config/services/clamav/enable 1"
  tags: Setup clamav

- name: Getting Minidlna Config
  template: src={{role_path}}/templates/configs/mindlna.josn dest=/tmp/mindlna.josn
  tags: repos

- name: Minidlna Config
  shell: omv-config -m /config/services/minidlna < /tmp/mindlna.josn
  tags: Setup minidlna
