---
#- name: Set network (hostname)
#  shell: omv-config --modify /config/system/network '{"hostname": "{{ servername }}","domainname": "","interfaces": "","iptables": ""}'
#  tags: Setup network

- name: Set network (enable hostname)
  shell: "omv-config --modify /config/system/omvextrasorg/modules/hostname 1"
  tags: Setup network

#- name: Seting timezone to UTC
#  shell: omv-config --modify /config/system/time/timezone "UTC"
#  tags: Setup timezone

#- name: Set Time zone server
#  shell: omv-config --modify /config/system/time/timeservers "{{ NTPSERVER1 }}"
#  tags: Setup timezone

#- name: Enable NTP
#  shell: "omv-config --modify /config/system/time/enable 1"
#  tags: Setup timezone

- name: Getting Minidlna Config
  template: src={{role_path}}/templates/configs/minidlna.josn dest=/tmp/minidlna.josn
  tags: Setup minidlna

- name: Getting clamav Config
  template: src={{role_path}}/templates/configs/clamav.josn dest=/tmp/clamav.josn
  tags: Setup clamav

- name: Getting couchpotato Config
  template: src={{role_path}}/templates/configs/couchpotato.josn dest=/tmp/couchpotato.josn
  tags: Setup couchpotato

- name: Getting downloader Config
  template: src={{role_path}}/templates/configs/downloader.josn dest=/tmp/downloader.josn
  tags: Setup downloader

- name: Getting sickbeard Config
  template: src={{role_path}}/templates/configs/sickbeard.josn dest=/tmp/sickbeard.josn
  tags: Setup sickbeard

- name: Minidlna Config
  shell: omv-config -m /config/services/minidlna "`cat /tmp/minidlna.josn`"
  tags: Setup minidlna

- name: Clamav Config
  shell: omv-config -m /config/services/clamav "`cat /tmp/clamav.josn`"
  tags: Setup clamav

- name: couchpotato Config
  shell: omv-config -m /config/services/couchpotato "`cat /tmp/couchpotato.josn`"
  tags: Setup couchpotato

- name: downloader Config
  shell: omv-config -m /config/services/downloader "`cat /tmp/downloader.josn`"
  tags: Setup downloader

- name: sickbeard Config
  shell: omv-config -m /config/services/sickbeard "`cat /tmp/sickbeard.josn`"
  tags: Setup sickbeard

#####Adding Groups########
- name: Adding groups
  group: 
   name: "{{ item }}" 
   state: present
  with_items: "{{ user_groups }}"   

#####Adding Users########
- name: Adding users
  user: 
   name: "{{ item.key }}" 
   groups: "{{ item.value.groups }}"
   append: yes
   password: "{{ item.value.password }}" 
  with_dict: "{{ users_accounts }}"

- name: Creating SSH-key folder
  file: 
   path: /home/{{ item.key }}/.ssh 
   state: directory
  with_dict: "{{ users_accounts }}"

- name: Creating SSH-key file
  copy: 
   content: "{{ item.value.key }}" 
   dest: /home/{{ item.key }}/.ssh/authorized_keys
  with_dict: "{{ users_accounts }}"